server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  redis:
    host: www.haojunqian.cn
    password: 19970829hh
